#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.
## style-ok: no-strict
## Explicit strict options set; global 'export LC_ALL=C' omitted by design (locale forced per-command).

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

systemctl --no-pager --no-block status sysmaint-boot.service
